version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      # POSTGRES_USER: ecom
      # POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
